services:
  ui:
    build:
      context: .
    ports:
      - '4200:4200'
    volumes:
      - .:/dev-tech-blog-ui
      - /dev-tech-blog-ui/node_modules
    command: ng serve --host 0.0.0.0
    stdin_open: true
    networks:
      - dev-tech-blog-net

networks:
  dev-tech-blog-net:
    name: dev-tech-blog-net
    external: true
